limits:
  tagMaxLength: 4
  nameMaxLength: 16

filter:
  allowedTagRegex: "^[A-Za-z0-9]{1,4}$"
  allowedNameRegex: "^[A-Za-z0-9 _]{1,16}$"
  blockedWords:
    - "admin"
    - "mod"
    - "owner"

points:
  startPoints: 1000
  minPoints: 0
  maxPoints: 100000
  killScaling:
    baseReward: 20.0
    factor: 0.02
    minChange: 5
    maxChange: 50
  selfDeathLoss:
    defaultLoss: 10
    causes:
      FALL: 15
      LAVA: 20
      DROWNING: 20
      FIRE: 15
      FIRE_TICK: 15
      ENTITY_EXPLOSION: 20
      BLOCK_EXPLOSION: 20
      STARVATION: 25
      CONTACT: 10

ui:
  skullSymbol: "\uD83D\uDC80"
  titles:
    kill:
      title: "<symbol> ZABOJSTWO <symbol>"
      subtitleKiller: "+<delta_killer> | <points_killer_after> pkt"
      subtitleVictim: "-<delta_victim> | <points_victim_after> pkt"
    selfDeath:
      title: "<symbol> SMIERC <symbol>"
      subtitle: "-<delta_victim> | <points_victim_after> pkt"
    timings:
      fadeIn: 10
      stay: 40
      fadeOut: 10
  messages:
    # przeniesione do messages.yml

clan:
  pvpDefault: true
  upgrades:
    guiTitle: "<YELLOW>Ulepszenia klanu"
    member:
      baseLimit: 8
      step: 2
      maxLevel: 5
      costs: [8, 12, 16, 20, 24]
      itemName: "<GOLD>Limit czlonkow"
      itemLore:
        - "<GRAY>Zwieksza maksymalna liczbe czlonkow klanu"
    ally:
      baseLimit: 1
      step: 1
      maxLevel: 5
      costs: [6, 10, 14, 18, 22]
      itemName: "<GREEN>Limit sojuszy"
      itemLore:
        - "<GRAY>Zwieksza liczbe sojusznikow"
  info:
    title: "<DARK_GREEN>\u25c6 <GREEN>Informacje o klanie"
    lines:
      - "<GOLD>\u2606 <WHITE>Nazwa: <YELLOW><clan_name> <GRAY>[<clan_tag>]"
      - "<AQUA>\u2736 <WHITE>Punkty: <AQUA><clan_points>"
      - "<YELLOW>\u265b <WHITE>Lider: <GOLD><clan_leader>"
      - "<GREEN>\u27a4 <WHITE>Zastepcy: <clan_officers>"
      - "<GOLD>\ud83d\udc65 <WHITE>Czlonkowie: <GOLD><members_used>/<members_limit> <GRAY><clan_members>"
      - "<GREEN>\u2694 <WHITE>Sojusznicy: <GREEN><ally_used>/<ally_limit> <GRAY><clan_allies>"
      - "<RED>\u2727 <WHITE>PvP: <clan_pvp>"
  # clan.currency automatycznie zapisze sie po pierwszym uruchomieniu / komendzie setcoin

ranking:
  pageSize: 10
  playerFormat: "<YELLOW>#<position> <WHITE><player_name> <GRAY>- <AQUA><points> pkt"
  playerFormatSelf: "<GOLD>#<position> <WHITE><player_name> <GRAY>- <GREEN><points> pkt"
  clanFormat: "<YELLOW>#<position> <WHITE><clan_display> <GRAY>- <AQUA><points> pkt"
  clanFormatSelf: "<GOLD>#<position> <WHITE><clan_display> <GRAY>- <GREEN><points> pkt"
  killCooldownSeconds: 1800
  ignoreSameIp: true

placeholders:
  noClanText: "-"

storage:
  type: "sqlite"
  file: "plugins/Fepbox-Klany/data.db"


